import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Kanban | Login or Sign Up",
  description: "Generated by create next app",
};

export default async function layout({
  children,
}: {
  children: React.ReactElement;
}) {
  return (
    <div className="min-h-screen grid grid-cols-2">
      <div className=" bg-white">
        <div className=" flex flex-col mt-auto h-full bg-gray-50">
          <div className="px-3 py-4 flex flex-row items-center gap-3">
            <img
              src="https://kanban-task-management-app.netlify.app/static/media/logo-mobile.e60c2fbc3dcefa4256e0569ffba5e523.svg"
              className="w-[5%]"
              alt="Kanban Logo"
            />
            <h1 className="text-3xl font-semibold">kanban</h1>
          </div>

          <div className=" self-center my-auto px-10">
            <p>
              “This Kanban board has completely transformed how I manage my
              projects — it keeps my workflow organized and helps me deliver
              results faster and with less stress.” – Sofia Davis
            </p>
          </div>
        </div>
      </div>
      <div className="self-center">{children}</div>
    </div>
  );
}
